# Generated by Django 5.2.5 on 2025-08-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0016_globalresponse_source_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiveconfiguration',
            name='xai_api_key',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='singlepromptchat',
            name='vendor',
            field=models.IntegerField(choices=[(1, 'OPEN_AI'), (2, 'OLLAMA'), (3, 'XAI')], default=1),
        ),
    ]
