# Generated by Django 5.2.5 on 2025-08-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0017_alter_hiveconfiguration_xai_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiveconfiguration',
            name='xai_api_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
